### PR TITLE
Update revChatGPT version

### PR DESCRIPTION
**Pull request by djerryz**
see #104

### CODE REVIEW

**Review by acheong08 — APPROVED** [review]
The API remains the same so no bugs will occur if you update. Only improvements

**Comment by acheong08** [comment]
The login problem is due to network issues (especially in China where it is blocked). You can fix this with a proxy

**Comment by OliverGrace** [comment]
> The login problem is due to network issues (especially in China where it is blocked). You can fix this with a proxy (Which is supported by the new version)

@acheong08 Nope, on a US server it still cannot login with email and password.

**Comment by acheong08** [comment]
Try with debug enabled. It is working for me via a VPN

**Comment by acheong08** [comment]
The bug here is that the email and password aren't escaped properly

**Comment by acheong08** [comment]
There is a second unnecessary login function called as well

**Comment by acheong08** [comment]
Also doesn't work when you are the speaker

**Comment by acheong08** [comment]
Remember to remove session token from config

**Comment by fuergaosi233** [comment]
CleanShot 2022-12-09 at 17 56 02@2x
I think even with the old version, it still works fine.

**Comment by RealTong** [comment]
I'm using `0.0.27` and I can't log in.

Upgrading revChatGPT to `0.0.33.5` did solve the login problem

Thanks!😉

**Comment by lushenle** [comment]
> The login problem is due to network issues (especially in China where it is blocked). You can fix this with a proxy (Which is supported by the new version)

This does not appear to be an error caused by a network issue, my docker environment uses vps in the New York region, that was also this error

**Comment by acheong08** [comment]
> This does not appear to be an error caused by a network issue, my docker environment uses vps in the New York region, that was also this error

Possible captcha? The library doesn't support captcha yet

**Comment by lushenle** [comment]
> > This does not appear to be an error caused by a network issue, my docker environment uses vps in the New York region, that was also this error
> 
> Possible captcha? The library doesn't support captcha yet

captcha？

My network access to ChatGPT is very smooth

**Comment by fuergaosi233** [comment]
Thanks for your PR, but since no one responded to Comment, to fix this problem as soon as possible, I can only submit a new PR.🙏

**Pull request closed without merging**
